<!DOCTYPE html >
<html xmlns="http://www.w3.org/1999/xhtml" lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Pragma" content="no-cache">
    <META    HTTP-EQUIV="Cache-Control" CONTENT="no-cache">
    <META    HTTP-EQUIV="Expires" CONTENT="0">

    <title>SmartPetFeeder喂食设置</title>

<!-- The main CSS file -->
<link href="../css/clockadder_style.css" rel="stylesheet"/>
<link rel="icon" href="../images/fav.png" type="image/x-icon"/>
<!--[if lt IE 9]>
    <script src="../js/html5.js"></script>
    <![endif]-->
</head>

<body>
<div style="width:100%; height: 100%">
    <div id='div1' style="width:12%; float:left; height: 1000px; background: #389dc1;">
    <form action="clockadder.php" method="post">
        <nav>
	    <div class="person">
		    <div class="name">
                <div id="user_name" class="user_name"></div>
                <div class="arrows" id="arrow1"><img src="../images/arrows-down.png" alt="箭头" draggable="false"/></div>
		    </div>
	    </div>
        <div class="alert" style="margin-right: 3%;" id="alert1"><a href="../index.html">退出</a></div>
        </nav>
	<input type="submit" class="change" name="change"     id="set feed" value="喂食设置"/>
    <input type="submit" class="change" name="change"     id="pet pic"  value="宠物照片"/>
    <input type="submit" class="change" name="change"     id="eat stat" value="饮食情况"/>
    <input type="submit" class="change" name="change"     id="warn"     value="报警信息"/>
    </form>
    </div>
    <div id='div2' class="main_part" style="width:80%; height:50%; overflow:hidden;">
<!-- The dialog is hidden with css -->
        <div id="'setting" style="text-align:center;">
            <form id="alarm-dialog" action="clockadder.php" method="post">

            <h2 style="margin:0px auto; font-size: 30px;">设定喂食时间</h2>

            <label class="hours">
                小时
                <input type="number" name='hour' value="0" min="0" />
            </label>

            <label class="minutes">
                分钟
                <input type="number" name='minute' value="0" min="0" />
            </label>

            <label class="seconds">
                出粮量(g)
                <input type="number" name='weight' value="0" min="0" />
            </label>
                <input type='submit' id="alarm-set" name='set' class="button blue" value="设置"/>
                <input type='submit' id="alarm-clear" name='clear' class="button red" value="清除"/>

        </form>
        </div>
        <div id="scrolling" class="scrolled_information">
            <h2> 喂食时间 喂食量</h2>
            <div style="width:100%; height:400px; background:#CCCCCC; overflow:hidden; position:relative; left:0; top:0; word-wrap:break-word;" class="aa" id="test_container">
                <!--# 滚动内容-->
                <div style="position:relative; top:0;" id="test_shower">
                </div>
            </div>
            <div style="position:relative; display:none; left:300px; top:0; width:20px; height:400px; -moz-user-focus:ignore;-moz-user-input:disabled;-moz-user-select:none;" id="test_scroller">
                <div style="position:relative; background:#999999; width:100%; height:20px; left:0; top:0;" id="test_scroll_up"></div>
                <div style="position:relative; width:20px; height:100px; background:#000000; left:0; top:20px;" id="test_scroll_bar"></div>
                <div style="position:relative; background:#999999; width:100%; height:20px; left:0; bottom:0;" id="test_scroll_down"></div>
            </div>
        </div>
</div>
</div>

<!-- JavaScript Includes -->
<script type="text/javascript" src="../js/jquery-1.8.3.min.js"></script>
<script src="../js/moment.min.js"></script>
<script type="text/javascript">
		let theID =	'<?php $s= $_COOKIE['username']; echo $s; ?>';
        $(document).ready(function() {
            $('#user_name').html(theID);
            $("#arrow1").click(function(){
                $("#alert1").toggle();
            });
        });
        $("#arrow1").click(function(){
            $("#alert1").toggle();
        });
</script>
<script src="../js/clockadder_script.js"></script>

</body>
</html>
