<!DOCTYPE html>
<html lang="en">
<link href="../css/warn.css" rel="stylesheet"/>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Pragma" content="no-cache">
    <META    HTTP-EQUIV="Cache-Control" CONTENT="no-cache">
    <META    HTTP-EQUIV="Expires" CONTENT="0">
    <link rel="icon" href="../images/fav.png" type="image/x-icon"/>
    <title>warn</title>
</head>
<body>
<div style="width:100%">
    <form id='div1' style="width:12%; float:left; height: 1000px; background: #389dc1;" action="warn.php" method="post">
        <nav>
        <div class="person">
            <div class="name">
                <div id="user_name" class='user_name' style="height: 20px;"></div>
                <div class="arrows" id="arrow1"><img src="../images/arrows-down.png" alt="箭头" draggable="false"/></div>
            </div>
        </div>
            <div class="alert" style="margin-right: 3%;" id="alert1"><a href="../index.html">退出</a></div>
        </nav>
        <input type="submit" class="change" name="change"     id="set feed" value="喂食设置"/>
        <input type="submit" class="change" name="change"     id="pet pic"  value="宠物照片"/>
        <input type="submit" class="change" name="change"     id="eat stat" value="饮食情况"/>
        <input type="submit" class="change" name="change"     id="warn"     value="报警信息"/>
    </form>

    </form>
    <div id='div2' class="main_part" style="width:80%; height:50%; overflow:hidden; ">
        <h2 style="margin:50px auto; text-align:center; font-size: 30px;">报警信息</h2>
        <!--<div id="'setting" style="text-align:center;">
            <form id="alarm-dialog" action="getwarn.php" method="post">

                <h2 style="margin:0px auto; font-size: 30px;">报警信息</h2>

                <label class="year">
                    年份
                    <input type="number" name='year' value="2021" min="1970" />
                </label>

                <label class="month">
                    月份
                    <input type="number" name='month' value="1" min="1" />
                </label>

                <label class="day">
                    日期
                    <input type="number" name='day' value="1" min="1" />
                </label>
                <input type='submit' id="alarm-set" name='set' class="button blue" value="设置"/>
                <input type='submit' id="alarm-clear" name='clear' class="button red" value="清除"/>

            </form>
        </div>-->
        <div id="scrolling" class="scrolled_information">
            <h2> 报警时间 报警类别</h2>
            <div style="margin-top:0px; width:100%; height:400px; background:#CCCCCC; overflow:hidden; position:relative; left:0; top:0; word-wrap:break-word;" class="aa" id="test_container">
                <!--# 滚动内容-->
                <div style="position:relative; top:0;" id="test_shower">
                </div>
            </div>
            <div style="position:relative; display:none; left:300px; top:0; width:20px; height:400px; -moz-user-focus:ignore;-moz-user-input:disabled;-moz-user-select:none;" id="test_scroller">
                <div style="position:relative; background:#999999; width:100%; height:20px; left:0; top:0;" id="test_scroll_up"></div>
                <div style="position:relative; width:20px; height:100px; background:#000000; left:0; top:20px;" id="test_scroll_bar"></div>
                <div style="position:relative; background:#999999; width:100%; height:20px; left:0; bottom:0;" id="test_scroll_down"></div>
            </div>
        </div>
    </div>
</div>
<!-- JavaScript Includes -->
<script type="text/javascript" src="../js/jquery-1.8.3.min.js"></script>
<script src="../js/moment.min.js"></script>
<script type="text/javascript">
    let theID =	'<?php $s= $_COOKIE['username']; echo $s; ?>';
    $(document).ready(function() {
        $('#user_name').html(theID);

        let targeturl = 'getwarn.php';
            //+ '?myid='+theID+ '&data='+dataTYPE+'&day='+day+'&month='+month+'&year='+year;
        let scroll=document.getElementById("test_shower");
        setInterval(async function() {
            console.log(scroll.childNodes.length);
            for (let i=0; i<scroll.childNodes.length;i++){
                let childNode = scroll.childNodes[0]; //总是删除第一个，是不是更简单
                scroll.removeChild(childNode);
            }
            for (let i=0; i<scroll.childNodes.length;i++){
                let childNode = scroll.childNodes[0]; //总是删除第一个，是不是更简单
                scroll.removeChild(childNode);
            }
            for (let i=0; i<scroll.childNodes.length;i++){
                let childNode = scroll.childNodes[scroll.childNodes.length-1-i]; //总是删除第一个，是不是更简单
                scroll.removeChild(childNode);
            }
            console.log(scroll.childNodes.length);
            await $.getJSON( targeturl,
                function(data){
                    console.log(data);
                    let set_result = [];

                    for(let i=0;i<Math.min(data['warn_date'].length-1,5);i++){
                        let warndate = data['warn_date'][i];
                        let warntime = data['warn_time'][i];
                        let warntype = data['warn_label'][i];
                        let warning='';
                        if(warntype==='people'){
                            warning='有人靠近';
                        }
                        let warn_child = document.createElement("div");
                        warn_child.setAttribute('class','warn_information');
                        set_result.push({"time":warntime,"warn":warning});
                        warn_child.innerHTML=warndate+' &nbsp; '+warntime+' &nbsp; '+warning;
                        scroll.appendChild(warn_child);
                    }
                });
        }, 1000);
    });
</script>
<script src="../js/warn.js"></script>

</body>
</html>